### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [dpressel/n3rd#2]
Hello, under what license is this project released under ? Thank-you.

**Comment by dpressel** [comment]
The license is Apache License 2.0, though, I am not really maintaining this project at the moment.  As far as highly flexible and performant DL frameworks, I would suggest looking into something like TensorFlow, where you can train the software in Python and do inference with TensorFlow serving or through the Java JNI bindings.  Alternately, DyNet, has Scala/Java bindings.  You could also look into deeplearning4j, though I have not tried it myself.
